"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard from './dashboard.bones.json'
import _transactions from './transactions.bones.json'
import _accounts from './accounts.bones.json'
import _bills from './bills.bones.json'
import _budgets from './budgets.bones.json'
import _reports from './reports.bones.json'
import _settings from './settings.bones.json'

configureBoneyard({"color":"#e5e5e5","darkColor":"#2a2a2a","animate":"shimmer","shimmerColor":"#ebebeb","darkShimmerColor":"#333333","speed":"1.8s","transition":300})

registerBones({
  "dashboard": _dashboard,
  "transactions": _transactions,
  "accounts": _accounts,
  "bills": _bills,
  "budgets": _budgets,
  "reports": _reports,
  "settings": _settings,
})
